# -*- coding: utf-8 -*-
"""Final Skin Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qz_FevZal-K5CDYqkFL2no_cHk3AHtpU
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout, BatchNormalization, Input
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping
import os

from google.colab import drive
drive.mount('/content/drive')

train_dir = "/content/drive/MyDrive/Skin dataset 15/Dataset/train"
test_dir = "/content/drive/MyDrive/Skin dataset 15/Dataset/test"

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest'
)

test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(192, 192),
    batch_size=32,
    class_mode='categorical'
)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=(192, 192),
    batch_size=32,
    class_mode='categorical'
)

num_classes = len(train_generator.class_indices)

train_generator.class_indices

base_model = MobileNetV2(
    input_shape=(192,192,3),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = True
for layer in base_model.layers[:-20]:
    layer.trainable = False

inputs = Input(shape=(192,192,3))
x = base_model(inputs, training=False)
x = GlobalAveragePooling2D()(x)
x = BatchNormalization()(x)
x = Dense(512, activation='relu')(x)
x = Dropout(0.4)(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.3)(x)
outputs = Dense(num_classes, activation='softmax')(x)

model = Model(inputs, outputs)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

print(model.summary())

history = model.fit(
    train_generator,
    validation_data=test_generator,
    epochs=80
)

model.save("final_skin_model.keras", include_optimizer=False)
print("✅ Model saved successfully!")

