# -*- coding: utf-8 -*-
"""Skin Types Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F28-PQVit-fquFWtLs6PslWf6JD2pUcE
"""

import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.layers import Dense, GlobalAveragePooling2D, Dropout, Input
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam

from google.colab import drive
drive.mount('/content/drive')

train_dir = "/content/drive/MyDrive/Skin Types Dataset 1/Oily-Dry-Skin-Types/train"
val_dir = "/content/drive/MyDrive/Skin Types Dataset 1/Oily-Dry-Skin-Types/valid"
test_dir = "/content/drive/MyDrive/Skin Types Dataset 1/Oily-Dry-Skin-Types/test"

train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True,
    width_shift_range=0.2,
    height_shift_range=0.2
)
val_datagen = ImageDataGenerator(rescale=1./255)
test_datagen = ImageDataGenerator(rescale=1./255)

train_gen = train_datagen.flow_from_directory(
    train_dir,
    target_size=(192,192),
    batch_size=32,
    class_mode='categorical'
)
val_gen = val_datagen.flow_from_directory(
    val_dir,
    target_size=(192,192),
    batch_size=32,
    class_mode='categorical'
)
test_gen = test_datagen.flow_from_directory(
    test_dir,
    target_size=(192,192),
    batch_size=32,
    class_mode='categorical'
)

inputs = Input(shape=(192,192,3))
base_model = MobileNetV2(weights='imagenet', include_top=False, input_tensor=inputs)
base_model.trainable = False

x = base_model.output
x = GlobalAveragePooling2D()(x)
x = Dropout(0.3)(x)
x = Dense(128, activation='relu')(x)
outputs = Dense(3, activation='softmax')(x)

model = Model(inputs=inputs, outputs=outputs)

model.compile(optimizer=Adam(1e-4), loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

history = model.fit(train_gen, validation_data=val_gen, epochs=15)

test_loss, test_acc = model.evaluate(test_gen)
print(f"✅ Test Accuracy: {test_acc*100:.2f}%")

model.save("skin_type_model.keras")
print("✅ Model Saved Successfully!")

